### ISSUE TITLE
Details on how ControlNet is used

### ISSUE THREAD

**Issue by tomtastico** [Nutlope/roomGPT#1]
Thanks for this awesome example!

It would be great if you could also explain how you are using ControlNet. What kind of extra input are you adding on top of the photo itself, to better control the output? Inferred depth? Straight line detection? 

Also the model doesn't seem to be public in Replicate, is that right? It would be great if it was 😃 

Thank you again for making the client site itself open source! 😄

**Comment by hqman** [comment]
Thanks for your work！！！
 I would also like to know which model on replicate platform  was used?

**Comment by hqman** [comment]
I run the code and found that the model was used  https://replicate.com/jagilley/controlnet-hough

**Comment by Nutlope** [comment]
The replicate model is here! https://replicate.com/jagilley/controlnet-hough

Not adding any extra input besides a custom prompt which you can find in the `pages/api/generate.tsx` file. Closing for now but feel free to re-open if you have any other questions.

**Comment by gelinger777** [comment]
@Nutlope  is 854e8727697a057c525cdb45ab037f64ecca770a1769cc52287c2e56472a247b    in the code is  shortcode for https://replicate.com/jagilley/controlnet-hough ?
