### ISSUE TITLE
Generate Getting 500 server error. How to solve this issue.

### ISSUE THREAD

**Issue by krishnamaurya-96** [Nutlope/roomGPT#109]
When add image facing this issue.

Unhandled Runtime Error
SyntaxError: Unexpected end of JSON input
app\dream\page.tsx (91:29) @ json

  89 | });
  90 |
> 91 | let newPhoto = await res.json();
     |                         ^
  92 | if (res.status !== 200) {
  93 |   setError(newPhoto);
  94 | } else {

Also getting /generate 500 error .

How to solve this issue?

**Comment by krishnamaurya-96** [comment]
Fixed

**Comment by xxalan** [comment]
I met the same problem, please tell me how you solved it

**Comment by krishnamaurya-96** [comment]
In my case downgrade node version 18.16.1 and and also check .env file API details variable name there be KEY instead of TOKEN.
This is works only when you facing  "/generate getting 500 error".

**Comment by Albuseven** [comment]
> I met the same problem, please tell me how you solved it

same problem to me, have you solved it ?
