### ISSUE TITLE
After uploading the picture, it is prompted error

### ISSUE THREAD

**Issue by gl-guoliang** [Nutlope/roomGPT#13]
API has been generated and configured in the ENV file
After uploading the picture, there is an error in the picture

<img width="966" alt="image" src="https://user-images.githubusercontent.com/81785354/223000142-ba7b8c65-3ece-4e04-8dce-f9526bda3703.png">

**Comment by layerkugou** [comment]
good

**Comment by Coderdivine** [comment]
Error says "Can't read value of undefined get", To avoid error try this: ` if(!jsonStartresponse || !jsonStartResponse.urls) console.error("Request Couldn't be completed")`

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out!
