### ISSUE TITLE
Image Generation Very Slow Loading or Not at All

### ISSUE THREAD

**Issue by brianzajac** [Nutlope/roomGPT#19]
Firstly, thanks for making this open source. I've added my API in the .env file, but my image generation is either too slow or does not come up at all. Looking at the error logs I see a 504 timeout error along with:

polling for result...
polling for result...
polling for result...
polling for result...
polling for result...
polling for result...
polling for result...
polling for result...
polling for result...

Is there something I am missing? Is there something I can do to make this faster?

Some additional info that may help:
- Cold Boot Duration is 195ms
- Image successfully posts on Replicate
- Deployment status shows no issues

**Comment by Nutlope** [comment]
Hi, does it work locally? And are you using Vercel? If you're using Vercel, make sure you're adding the env variable to your Vercel project.

**Comment by brianzajac** [comment]
Thanks to your project, I decided to start developing myself (I'm a designer) & signed up using Vercel. That being said, I haven't successfully implemented the "NPM" functions you mentioned in the readme. I've tried to VS code, VS, GitBash & Git command line with no luck. 

I did install your project through Vercel, followed the steps, removed the example ENV file & changed it to what you see below:
![apienv](https://user-images.githubusercontent.com/118024211/223446064-91797c16-f8c2-4989-9f40-963f82de5e0a.jpg)

Since then I Git cloned my project locally (again without the NPM functions) and it does successfully deploy. If you need the deploy link, I can DM you on Twitter.

**Comment by muktoxxx** [comment]
Hlw can you help regards deploying locally how did you deploy this one?? I tried on ubuntu but when i run npm run dev it says sh-1 file cannot find something like this... Plz need help...

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
