### ISSUE TITLE
Auth Setup

### ISSUE THREAD

**Issue by iShelar** [Nutlope/roomGPT#29]
I did not understand auth setup clearly.

**Comment by jinkexue** [comment]
does the project run locally?or need to connect to other server?
env file  says optional for other setting except apikey

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
