### ISSUE TITLE
Unable to get any output on website

### ISSUE THREAD

**Issue by rajathooda** [Nutlope/roomGPT#31]
I tried using the website for the first time today, uploaded an image and just saw a blank panel. tried again but it used up all three of my tries trying to get this to display an image. 

<img width="950" alt="image" src="https://user-images.githubusercontent.com/127722895/224629186-ef2b0927-2e2f-46c7-a2de-1bd67d18d229.png">

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
