### ISSUE TITLE
Cannot find the DB URL and SHADOW DB URL from Neon

### ISSUE THREAD

**Issue by Niuecl** [Nutlope/roomGPT#32]
Try to follow the guide to install, but block in "Auth setup" step #2 "Add DB URL and SHADOW DB URL from Neon"
Can help to clarify where can find the DB URL and SHADOW DB URL from Neon?

**Comment by fewjative** [comment]
These come from creating a account on https://neon.tech/. 

Shadow aspect is discussed here:
https://neon.tech/docs/guides/prisma#configure-a-shadow-database-for-prisma-migrate

**Comment by sblaque** [comment]
Is the pooled connection the shadow db?

**Comment by DuncanMatthews** [comment]
Also struggling with this
