### ISSUE TITLE
DATABASE_URL for local development

### ISSUE THREAD

**Issue by yfeng21** [Nutlope/roomGPT#37]
I added my Vercel API to .env, and can see the generated image in my Vercel dashboard, but my local server showed the following error, and thus I couldn't see the image from my locally-hosted website. In my .env, I only set REPLICATE_API_KEY, as DATABASE_URL was marked as optional
```
error - PrismaClientInitializationError: 
Invalid `prisma.room.create()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   | 
 2 |   provider          = "postgresql"
 3 |   url               = env("DATABASE_URL")

```

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
