### ISSUE TITLE
安装后无法正常使用？

### ISSUE THREAD

**Issue by zxs001002** [Nutlope/roomGPT#39]
E:\room\roomGPT>npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 1347 ms (204 modules)
wait  - compiling...
event - compiled successfully in 158 ms (168 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 59 ms (205 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling / (client and server)...
event - compiled client and server successfully in 108 ms (281 modules)
wait  - compiling /api/auth/[...nextauth] (client and server)...
event - compiled successfully in 79 ms (106 modules)
[next-auth][warn][NEXTAUTH_URL]
https://next-auth.js.org/warnings#nextauth_url
[next-auth][warn][NO_SECRET]
https://next-auth.js.org/warnings#no_secret

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Call Stack

可以帮忙处理解决一下吗
谢谢

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
