### ISSUE TITLE
"Unexpected Token '?'" on Fresh Ubuntu 22.04 install

### ISSUE THREAD

**Issue by tokenwizard** [Nutlope/roomGPT#4]
I spun up an LXC in ProxMox with an Ubuntu 22.04 template and ran through the installation steps:
`apt install npm git`
`git clone https://github.com/Nutlope/roomGPT`

created .env file with my API key

`npm install`
`npm run dev`

At this point, I receive the error shown below and the service fails to run. 

![image](https://user-images.githubusercontent.com/24832561/222738462-3ca1d420-e3c6-4fbf-92bd-5e3ce8376cce.png)

**Comment by ljwagerfield** [comment]
The nullish operator `??` was added in Node.js 14:

```
node --version
```

(Your version of Node.js version is probably <14.)

**Comment by tokenwizard** [comment]
Yeah, That is the issue. Good ol' Ubuntu. 

I'll spin up a more "modern" distro. 

Thanks.

**Comment by tokenwizard** [comment]
Might be worth noting that NodeJS >= 14 is required.

**Comment by tokenwizard** [comment]
Installed and running on archlinux base with no issues.
