### ISSUE TITLE
Prisma schema having issues on Vercel deployment

### ISSUE THREAD

**Issue by ex0rcist88** [Nutlope/roomGPT#48]
Unable to deploy on Vercel
--

Error: Prisma schema validation - (get-config wasm)
--
16:15:40.687 | Error code: P1012
16:15:40.688 | error: Environment variable not found: DIRECT_DATABASE_URL.
16:15:40.688 | -->  schema.prisma:4
16:15:40.688 | \|
16:15:40.688 | 3 \|   url               = env("DATABASE_URL")
16:15:40.688 | 4 \|   directUrl         = env("DIRECT_DATABASE_URL")
16:15:40.689 | \|
16:15:40.689 |  
16:15:40.689 | Validation Error Count: 1
16:15:40.689 | [Context: getConfig]
16:15:40.689 |  
16:15:40.689 | Prisma CLI Version : 4.11.0
16:15:40.754 | Error: Command "npm run build" exited with 1
16:15:40.974 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

**Comment by Niuecl** [comment]
I added DIRECT_DATABASE_URL to .env file to fixed this issue. May be it can help you

**Comment by ex0rcist88** [comment]
Seems to still have the same error though. Any ideas?

Error: Prisma schema validation - (get-config wasm)
--
20:51:12.727 | Error code: P1012
20:51:12.728 | error: Environment variable not found: DIRECT_DATABASE_URL.
20:51:12.728 | -->  schema.prisma:4
20:51:12.728 | \|
20:51:12.728 | 3 \|   url               = env("DATABASE_URL")
20:51:12.729 | 4 \|   directUrl         = env("DIRECT_DATABASE_URL")
20:51:12.729 | \|
20:51:12.729 |  
20:51:12.729 | Validation Error Count: 1
20:51:12.729 | [Context: getConfig]
20:51:12.729 |  
20:51:12.729 | Prisma CLI Version : 4.11.0
20:51:12.796 | Error: Command "npm run build" exited with 1
20:51:13.022 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

**Comment by ex0rcist88** [comment]
I added it to example.env and appended it as a required env variable in vercel. 
What is the value though?

**Comment by jetlej** [comment]
+1

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
