### ISSUE TITLE
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by Niuecl** [Nutlope/roomGPT#49]
There are continue return "WebSocket connection failed to call." error in debug panel:
websocket.js?a9be:60 WebSocket connection to 'wss://domain.comm/_next/webpack-hmr' failed

it does not happen in localhost

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
