### ISSUE TITLE
Troubleshooting a login error in a local project:"Try signing in with a different account"

### ISSUE THREAD

**Issue by NovemberJuliet** [Nutlope/roomGPT#50]
## error:Try signing in with a different account

- I chose to run this project locally and completed the deployment according to the steps. But after opening the project interface, clicking login prompts “Try signing in with a different account.”, and the following error occurred in the running state. How can I solve this? I look forward to your reply.

![screenshot_20230327013506](https://user-images.githubusercontent.com/41661643/227793693-7f27ef2f-47c1-44e6-aed3-7384999ce059.png)

    PS E:\stable diffusion\roomGPT> npm run dev
    
    > dev
    > next dev
    
    ready - started server on 0.0.0.0:3000, url: http://localhost:3000
    info  - Loaded env from E:\stable diffusion\roomGPT\.env.local
    info  - Using wasm build of next-swc
    warn  - Attempted to load @next/swc-win32-x64-gnu, but it was not installed
    warn  - Attempted to load @next/swc-win32-x64-msvc, but an error occurred: \\?\E:\stable diffusion\roomGPT\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node is not a valid Win32 application.
    \\?\E:\stable diffusion\roomGPT\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node
    event - compiled client and server successfully in 1624 ms (204 modules)
    wait  - compiling...
    event - compiled successfully in 148 ms (168 modules)
    wait  - compiling / (client and server)...
    event - compiled client and server successfully in 169 ms (282 modules)
    wait  - compiling /api/auth/[...nextauth] (client and server)...
    event - compiled successfully in 146 ms (106 modules)
    [next-auth][warn][NEXTAUTH_URL]
    https://next-auth.js.org/warnings#nextauth_url
    [next-auth][warn][NO_SECRET]
    https://next-auth.js.org/warnings#no_secret
    wait  - compiling /dream...
    event - compiled client and server successfully in 716 ms (1071 modules)
    wait  - compiling /api/remaining (client and server)...
    event - compiled successfully in 37 ms (130 modules)
    User not logged in
    wait  - compiling /api/auth/[...nextauth] (client and server)...
    event - compiled successfully in 17 ms (130 modules)
    [next-auth][error][SIGNIN_OAUTH_ERROR]
    https://next-auth.js.org/errors#signin_oauth_error outgoing request timed out after 3500ms {
      error: {
        message: 'outgoing request timed out after 3500ms',
        stack: 'RPError: outgoing request timed out after 3500ms\n' +
          '    at E:\\stable diffusion\\roomGPT\\node_modules\\openid-client\\lib\\helpers\\request.js:137:13\n' +
          '    at async Issuer.discover (E:\\stable diffusion\\roomGPT\\node_modules\\openid-client\\lib\\issuer.js:144:24)\n' +
          '    at async openidClient (E:\\stable diffusion\\roomGPT\\node_modules\\next-auth\\core\\lib\\oauth\\client.js:16:14)\n' +
          '    at async getAuthorizationUrl (E:\\stable diffusion\\roomGPT\\node_modules\\next-auth\\core\\lib\\oauth\\authorization-url.js:70:18)\n' +
          '    at async Object.signin (E:\\stable diffusion\\roomGPT\\node_modules\\next-auth\\core\\routes\\signin.js:38:24)\n' +
          '    at async AuthHandler (E:\\stable diffusion\\roomGPT\\node_modules\\next-auth\\core\\index.js:253:26)\n' +
          '    at async NextAuthHandler (E:\\stable diffusion\\roomGPT\\node_modules\\next-auth\\next\\index.js:24:19)\n' +
          '    at async E:\\stable diffusion\\roomGPT\\node_modules\\next-auth\\next\\index.js:60:32\n' +
          '    at async Object.apiResolver (E:\\stable diffusion\\roomGPT\\node_modules\\next\\dist\\server\\api-utils\\node.js:372:9)\n' +
          '    at async DevServer.runApi (E:\\stable diffusion\\roomGPT\\node_modules\\next\\dist\\server\\next-server.js:488:9)\n' +
          '    at async Object.fn (E:\\stable diffusion\\roomGPT\\node_modules\\next\\dist\\server\\next-server.js:751:37)\n' +
          '    at async Router.execute (E:\\stable diffusion\\roomGPT\\node_modules\\next\\dist\\server\\router.js:253:36)\n' +
          '    at async DevServer.run (E:\\stable diffusion\\roomGPT\\node_modules\\next\\dist\\server\\base-server.js:384:29)\n' +
          '    at async DevServer.run (E:\\stable diffusion\\roomGPT\\node_modules\\next\\dist\\server\\dev\\next-dev-server.js:743:20)\n' +
          '    at async DevServer.handleRequest (E:\\stable diffusion\\roomGPT\\node_modules\\next\\dist\\server\\base-server.js:322:20)',
        name: 'RPError'
      },
      providerId: 'google',
      message: 'outgoing request timed out after 3500ms'
    }

**Comment by Reb1rth7** [comment]
same

**Comment by javisolans** [comment]
same

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
