### ISSUE TITLE
You cannot specify "tags" in your file uploads that aren't whitelisted in the API key's settings (see "tag permissions" configured for this API key).

### ISSUE THREAD

**Issue by DzfSky** [Nutlope/roomGPT#55]
You cannot specify "tags" in your file uploads that aren't whitelisted in the API key's settings (see "tag permissions" configured for this API key).

**Comment by Estehsan** [comment]
Same issue!

**Comment by xiaoqibi** [comment]
I had the same problem

**Comment by Niuecl** [comment]
same issue.
I try to comment this line in dream.tsx file are work
//tags: [data?.remainingGenerations > 3 ? "paid" : "free"],

**Comment by narendrasngh995** [comment]
Need to comment the following line of code in dream.tsx file.
//tags: [data?.remainingGenerations > 3 ? "paid" : "free"],

**Comment by rapidstartup** [comment]
> Need to comment the following line of code in dream.tsx file. //tags: [data?.remainingGenerations > 3 ? "paid" : "free"],

Hmm, tried that. Not working

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
