### ISSUE TITLE
Question / Guidance

### ISSUE THREAD

**Issue by cesarve77** [Nutlope/roomGPT#57]
Firstly, I would like to extend my congratulations on creating such an excellent repository with roomGPT. The quality and functionality of your work have impressed me deeply, and I am truly inspired by what you have accomplished.

As a newcomer to the field of AI programming, I am eager to embark on a project of my own, and I was hoping you might be able to offer some guidance. I am particularly interested in developing something akin to roomGPT but with a more focused scope: specifically, I would like to create an AI tool that can change the color of walls in a room to a specified RGB value.

**Comment by Nutlope** [comment]
Thanks for the kind words! I would say experiment with Replicate models and see if you can get that working.
