### ISSUE TITLE
The input and output images were gone two days later

### ISSUE THREAD

**Issue by Niuecl** [Nutlope/roomGPT#58]
Generated the image is successful. However the input and output were gone after two days later in dashboard.

The records are in neon.tech. And copy the inputImage and outputImage url are return:
inputImage: 
{"error":{"message":"File not found (or you have insufficient privileges).","code":"file_not_found","details":{}}}
outputImage:
{"detail": "requested file not found"}

Is it register replicate is enough? or what any setting in replicate I was missing?

**Comment by fewjative** [comment]
Replicate automatically deletes any output after 24-48 hours.
