### ISSUE TITLE
Stripe-Webhook not returning event.

### ISSUE THREAD

**Issue by CAPTAIN320** [Nutlope/roomGPT#59]
Stripe setup successfully listens to the POST and registers event types.
However, the app itself does not detect those events.
Therefore, credits cannot be updated.
Please Help!

**Comment by R3P-tech** [comment]
Hey, I have the same issue. How did you solved that?

**Comment by CAPTAIN320** [comment]
I you have already setup the api keys, all you need to do is go to stripe dashboard > developers > test mode.
Then add http://localhost:3000/stripe-webhook as the webhook url.

**Comment by CAPTAIN320** [comment]
> Hey, I have the same issue. How did you solved that?

I you have already setup the api keys, all you need to do is go to stripe dashboard > developers > test mode.
Then add http://localhost:3000/stripe-webhook as the webhook url.

**Comment by R3P-tech** [comment]
I'm using vercel, with custom domain.
If i use:
https://mydomain.com/stripe-webhook
i get a 308 error
<img width="1214" alt="Capture d’écran 2023-04-23 à 22 43 11" src="https://user-images.githubusercontent.com/130335349/233849997-89a9591e-2c51-4c63-96b1-16f3584f10f4.png">

If i use:
https://www.mydomain.com/stripe-webhook
i get a 404 error
<img width="1214" alt="Capture d’écran 2023-04-23 à 22 41 14" src="https://user-images.githubusercontent.com/130335349/233850016-2b0cb944-8c9c-4a09-8e9d-465dd3f95cf6.png">

**Comment by CAPTAIN320** [comment]
> I'm using vercel, with custom domain. If i use: https://mydomain.com/stripe-webhook i get a 308 error <img alt="Capture d’écran 2023-04-23 à 22 43 11" width="1214" src="https://user-images.githubusercontent.com/130335349/233849997-89a9591e-2c51-4c63-96b1-16f3584f10f4.png">
> 
> If i use: https://www.mydomain.com/stripe-webhook i get a 404 error <img alt="Capture d’écran 2023-04-23 à 22 41 14" width="1214" src="https://user-images.githubusercontent.com/130335349/233850016-2b0cb944-8c9c-4a09-8e9d-465dd3f95cf6.png">

You need to add the full path of the stripe-webhook in your project. This means adding "api/"
In this case use the url:
https://{your domain}/api/stripe-webhook

**Comment by R3P-tech** [comment]
Working now, thanks !

**Comment by chakya** [comment]
@Kellokes have you made sure that the API key used is correct?
