### ISSUE TITLE
Unhandled Runtime Error when Generating Room 

### ISSUE THREAD

**Issue by tokenwizard** [Nutlope/roomGPT#6]
Service is running in fresh installed/updated archlinux base.
![image](https://user-images.githubusercontent.com/24832561/222758257-e180c28d-9927-4504-8a32-0ab480097657.png)

After Uploading a photo, this is the error displayed in the web interface:
![image](https://user-images.githubusercontent.com/24832561/222758083-eecff35c-165a-456e-8e03-6e436743940e.png)

And this is the related output in the terminal:
![image](https://user-images.githubusercontent.com/24832561/222757700-1054c18e-d90f-4a36-8c94-bb431667b707.png)

**Comment by brianzajac** [comment]
I am also getting a 504 timeout error. It posts in Replicate but not on the site. Any ideas?

**Comment by stepansalov** [comment]
I am getting the same error. Developer, let's please know, how to fix it.

**Comment by Nutlope** [comment]
Good to know!
