### ISSUE TITLE
How can I turn off Google Authorization？

### ISSUE THREAD

**Issue by DzfSky** [Nutlope/roomGPT#60]
How can I turn off Google Authorization？

**Comment by shafty023** [comment]
I also would like to know

**Comment by KAIYI-HSU** [comment]
Me too

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
