### ISSUE TITLE
Environment variable not found: DIRECT_DATABASE_URL.

### ISSUE THREAD

**Issue by sanye8899** [Nutlope/roomGPT#64]
npx prisma db push && prisma migrate dev && prisma generate
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DIRECT_DATABASE_URL.
  -->  schema.prisma:4
   | 
 3 |   url               = env("DATABASE_URL")
 4 |   directUrl         = env("DIRECT_DATABASE_URL")
   | 

Validation Error Count: 1

**Comment by mmtechhk** [comment]
I think it is the same answer as my previouse post
#56

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
