### ISSUE TITLE
deploy error after fullfill .env parameters

### ISSUE THREAD

**Issue by gumplus** [Nutlope/roomGPT#71]
Error info :

Running build in San Francisco, USA (West) – sfo1
--
18:57:30.576 | Cloning github.com/gumplus/room-GPT (Branch: main, Commit: e1e0dd1)
18:57:30.715 | Previous build cache not available
18:57:31.870 | Cloning completed: 1.294s
18:57:32.078 | Running "vercel build"
18:57:32.648 | Vercel CLI 28.18.5
18:57:32.968 | Installing dependencies...
18:57:39.377 | npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
18:57:39.647 | npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
18:57:43.315 | npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
18:57:58.619 |  
18:57:58.620 | > postinstall
18:57:58.620 | > prisma generate \|\| true
18:57:58.620 |  
18:57:59.515 | Environment variables loaded from .env
18:57:59.518 | Prisma schema loaded from prisma/schema.prisma
18:58:00.497 |  
18:58:00.498 | ✔ Generated Prisma Client (4.11.0 \| library) to ./node_modules/@prisma/client in 222ms
18:58:00.498 | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
18:58:00.498 | ```
18:58:00.498 | import { PrismaClient } from '@prisma/client'
18:58:00.498 | const prisma = new PrismaClient()
18:58:00.498 | ```
18:58:00.574 |  
18:58:00.574 | added 963 packages in 27s
18:58:00.574 |  
18:58:00.575 | 170 packages are looking for funding
18:58:00.575 | run `npm fund` for details
18:58:00.606 | Detected Next.js version: 13.1.6
18:58:00.619 | Detected `package-lock.json` generated by npm 7+...
18:58:00.620 | Running "npm run build"
18:58:01.026 |  
18:58:01.027 | > build
18:58:01.027 | > prisma generate && prisma migrate deploy && next build
18:58:01.027 |  
18:58:01.929 | Environment variables loaded from .env
18:58:01.932 | Prisma schema loaded from prisma/schema.prisma
18:58:02.950 |  
18:58:02.950 | ✔ Generated Prisma Client (4.11.0 \| library) to ./node_modules/@prisma/client in 235ms
18:58:02.950 | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
18:58:02.950 | ```
18:58:02.950 | import { PrismaClient } from '@prisma/client'
18:58:02.951 | const prisma = new PrismaClient()
18:58:02.951 | ```
18:58:05.145 | ┌─────────────────────────────────────────────────────────┐
18:58:05.146 | │  Update available 4.11.0 -> 4.12.0                      │
18:58:05.146 | │  Run the following to update                            │
18:58:05.146 | │    npm i --save-dev prisma@latest                       │
18:58:05.146 | │    npm i @prisma/client@latest                          │
18:58:05.146 | └─────────────────────────────────────────────────────────┘
18:58:06.084 | Environment variables loaded from .env
18:58:06.085 | Prisma schema loaded from prisma/schema.prisma
18:58:06.090 | Datasource "db": PostgreSQL database "neondb", schema "public" at "ep-wild-credit-819120.us-west-2.aws.neon.tech"
18:58:09.836 |  
18:58:09.836 | 5 migrations found in prisma/migrations
18:58:09.836 |  
18:58:10.228 |  
18:58:10.228 | No pending migrations to apply.
18:58:10.708 | info  - Loaded env from /vercel/path0/.env
18:58:10.884 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
18:58:10.884 | This information is used to shape Next.js' roadmap and prioritize features.
18:58:10.884 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
18:58:10.885 | https://nextjs.org/telemetry
18:58:10.886 |  
18:58:11.051 | info  - Linting and checking validity of types...
18:58:17.241 | info  - Creating an optimized production build...
18:58:31.393 | info  - Compiled successfully
18:58:31.393 | info  - Collecting page data...
18:58:31.786 | TypeError [ERR_INVALID_URL]: Invalid URL
18:58:31.786 | at new NodeError (node:internal/errors:400:5)
18:58:31.786 | at URL.onParseError (node:internal/url:565:9)
18:58:31.786 | at new URL (node:internal/url:645:5)
18:58:31.787 | at parseUrl (/vercel/path0/node_modules/next-auth/utils/parse-url.js:17:16)
18:58:31.787 | at Object.<anonymous> (/vercel/path0/node_modules/next-auth/react/index.js:72:34)
18:58:31.787 | at Module._compile (node:internal/modules/cjs/loader:1218:14)
18:58:31.787 | at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
18:58:31.787 | at Module.load (node:internal/modules/cjs/loader:1081:32)
18:58:31.787 | at Module._load (node:internal/modules/cjs/loader:922:12)
18:58:31.788 | at Module.require (node:internal/modules/cjs/loader:1105:19) {
18:58:31.788 | input: '',
18:58:31.788 | code: 'ERR_INVALID_URL'
18:58:31.788 | }
18:58:31.789 |  
18:58:31.789 | > Build error occurred
18:58:31.793 | Error: Failed to collect page data for /dashboard
18:58:31.793 | at /vercel/path0/node_modules/next/dist/build/utils.js:963:15
18:58:31.793 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
18:58:31.793 | type: 'Error'
18:58:31.794 | }
18:58:31.873 | Error: Command "npm run build" exited with 1
18:58:32.205 | Deployment completed
18:58:32.164 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

**Comment by alanlee9898** [comment]
Have you try adding NEXTAUTH_URL in your env?

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
