### ISSUE TITLE
Error: Prisma schema validation - (get-config wasm)

### ISSUE THREAD

**Issue by PopAI33** [Nutlope/roomGPT#72]
im getting this errro when deplyin in Vercel

i have my neon link and the replica api setup

please help

Error: Prisma schema validation - (get-config wasm)
--
03:14:20.651 | Error code: P1012
03:14:20.651 | error: Environment variable not found: DIRECT_DATABASE_URL.
03:14:20.651 | -->  schema.prisma:4
03:14:20.651 | \|
03:14:20.652 | 3 \|   url               = env("DATABASE_URL")
03:14:20.652 | 4 \|   directUrl         = env("DIRECT_DATABASE_URL")
03:14:20.652 | \|
03:14:20.652 |  
03:14:20.652 | Validation Error Count: 1
03:14:20.652 | [Context: getConfig]
03:14:20.653 |  
03:14:20.653 | Prisma CLI Version : 4.11.0
03:14:20.701 | Error: Command "npm run build" exited with 1
03:14:21.424 | Deployment completed
03:14:21.027 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

**Comment by badr2112** [comment]
Check other issues, this question has already been answered.

**Comment by TheRu27** [comment]
Same story

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
