### ISSUE TITLE
Request for "Delete User Data and Generated Images" Feature

### ISSUE THREAD

**Issue by AbdelAzizMohamedMousa** [Nutlope/roomGPT#79]
Dear RoomGPT team,

I'm writing to request a new feature for your website, [www.roomgpt.io](http://www.roomgpt.io/). As a user of your website, I value my privacy and the ability to control my personal data. While I appreciate the convenience and usefulness of your website, I would feel more comfortable if I had the option to delete my data from your servers when I no longer need it.

Therefore, I would like to request a "Delete User Data and Generated Images" feature that would allow users to delete their own data, photos, and generated images from the website. This feature would not only enhance the privacy and security of your users but would also help build trust between users and your website. Additionally, it would ensure compliance with data protection laws and regulations.

I hope you will consider my feature request and work towards implementing it soon. Thank you for your attention to this matter.

Best regards,

Abdelaziz Mohamed Mousa

**Comment by Nyx1on** [comment]
Hiii, i want to work on this feature.
