### ISSUE TITLE
Response never arrives on mobile device

### ISSUE THREAD

**Issue by bkoubik88** [Nutlope/roomGPT#82]
If I run the whole home on my computer, everything works. Also via WiFi. However, when I'm on the road, I don't get an answer when I upload a picture that I shot with the camera. If I look into the Replicate dashboard, however, the image is the same as the generated one. So it's up to you to send it back, why?

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
