### ISSUE TITLE
I never receive a generated image

### ISSUE THREAD

**Issue by AyandaAde** [Nutlope/roomGPT#90]
Hi, so I manage to upload an image but never get a newly generated image, it stays stuck on the loading process and the console log just keeps repeating "polling for result..." please help. 
![Screenshot (272)](https://github.com/Nutlope/roomGPT/assets/126201938/5c8e2f9d-bfd4-4e7a-8285-a9c8bea9b469)

![Screenshot (273)](https://github.com/Nutlope/roomGPT/assets/126201938/22565616-9a76-4aa2-acb4-e75bf1027ad8)

**Comment by zaynkazme** [comment]
Same problem

**Comment by AyandaAde** [comment]
Nevermind

**Comment by RiyaJain8114** [comment]
how was it resolved
